name: 'Prod Deployment'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  stage:
    name: 'Deployment Pipeline For Backend'
    runs-on: [self-hosted, Production-Motion]
    needs: ci
    steps:

      - name: 'Pull latest'
        working-directory: /var/www/vhosts/staging.saitalogistics.com/htdocs
        run: |
          sudo git pull

      - name: 'Full permission of Storage folder'
        working-directory: /var/www/vhosts/staging.saitalogistics.com/htdocs
        run: |
          sudo chmod -R 777 storage/ && sudo chown -R ubuntu:ubuntu .

      - name: Install Dependencies
        working-directory: /var/www/vhosts/staging.saitalogistics.com/htdocs
        run: composer

      - name: Compile CSS and Javascript
        working-directory: /var/www/vhosts/staging.saitalogistics.com/htdocs
        run: |
          npm install
          npm run prod
