name: Laravel

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install php -y
          composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: 'Pull latest'
        working-directory: /var/www/vhosts/staging.saitalogistics.com/htdocs
        run: |
          sudo git pull
