name: ci

# Controls when the workflow will run
on:
  pull_request:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-interaction --no-ansi --no-scripts --no-progress --prefer-dist

      - name: Compile assets
        run: |
          npm install
          npm run production

      - name: Generate key
        run: php artisan key:generate

      - name: Set up database
        run: |
          touch database/database.sqlite
          php artisan migrate --force
